name: PowerApps Quality Check and Package

on:
  push:
    branches:
      - main  # Replace with your main branch name

jobs:
  quality-check-and-package:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from GitHub repository
      - name: Checkout Code
        uses: actions/checkout@v2

      # Install Power Platform CLI
      - name: Install Power Platform CLI
        run: |
          npm install -g @powerapps/cli

      # Authenticate with PowerApps environment
      - name: Authenticate with PowerApps Environment
        run: pac auth create --url <your-environment-url> --username <your-username> --password <your-password>

      # Run code analysis using Power Platform CLI
      - name: Run PowerApps Code Analysis
        run: pac pcf scan --path <path-to-your-component-folder>

      # Check if code analysis has any errors
      - name: Check for Code Analysis Errors
        run: |
          if [[ $(pac pcf scan --path <path-to-your-component-folder> --json) =~ "\"numErrors\":0," ]]; then
            echo "Code analysis passed with no errors."
          else
            echo "Code analysis failed with errors."
            exit 1
          fi

      # Package the PowerApps app
      - name: Package PowerApps App
        run: pac pcf push --path <path-to-your-component-folder> --solution-name <your-solution-name> --skip-validation

      # Check if the package has been created successfully
      - name: Check Package Creation Status
        run: |
          if [[ $(pac solution list --json) =~ "\"solution_.+_\" ]]; then
            echo "Package created successfully."
          else
            echo "Package creation failed."
            exit 1
          fi
