name: PowerApps Code Quality and Packaging Check

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Power Platform CLI
        run: |
          npm install -g powerplatform-cli
      - name: Code Quality Check
        run: |
          pac pcf scan --path .
      - name: Confirm Package Build
        run: |
          pac solution list --details --json > solutions.json
          node -pe "JSON.parse(fs.readFileSync('solutions.json')).map(s => s.uniqueName).forEach(s => execSync(\`pac solution pack -n \${s}\`))"
