name: PowerApps Code Quality and Packaging Check

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Power Platform CLI
        run: |
          npm install -g pac-cli
      - name: Build Control and Perform Code Quality Check
        run: |
          pac pcf init --namespace <namespace> --name <name>
          cd <name>
          npm install
          npm run build
